name: 'Ecotone Framework'

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  run:
    name: "Testing Monorepo"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '8.1', '8.0' ]
        stability: [prefer-stable, prefer-lowest]
    services:
      rabbitmq:
        image: rabbitmq:3.8-alpine
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ecotone
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      localstack:
        image: localstack/localstack:0.8.10
        env:
          SERVICES: 'sqs,sns'
        ports:
          - '4576:4576'
          - '4575:4575'
      redis:
        image: redis:7-alpine
        ports:
          - '6379:6379'
    env:
      RABBIT_HOST: amqp://127.0.0.1:5672
      SQS_DSN: sqs:?key=key&secret=secret&region=us-east-1&endpoint=http://127.0.0.1:4576&version=latest
    steps:
    - name: PHP ${{ matrix.php-versions }} - ${{ matrix.stability }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Install dependencies
      run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

    - name: Test Behat on 8.0
      run: vendor/bin/behat -vvv -s event-sourcing
      env:
        DATABASE_DSN: pgsql://ecotone:secret@127.0.0.1:5432/ecotone
        SQS_DSN: sqs:?key=key&secret=secret&region=us-east-1&endpoint=http://127.0.0.1:4576&version=latest
        REDIS_DSN: redis://127.0.0.1:6379